import { Toaster } from 'react-hot-toast'
import { Inter } from 'next/font/google'
import { StoreProvider } from '@/providers/StoreProvider'
import { SearchProvider } from '@/shared/context/SearchContext'
import type { Metadata } from 'next'
import '@/shared/assets/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bonnitto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <SearchProvider>
            <Toaster position="top-center" />
            {children}
            
          </SearchProvider>
        </StoreProvider>
      </body>
    </html>
  )
}